### ISSUE TITLE
idea运行出现错误

### ISSUE THREAD

**Issue by 1029124370** [fanchaoo/netease-cloud-music-community#7]
`Exception in thread "restartedMain" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE_ALL] - Failed to create parent directories for [/var/log/live/log.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE_ALL] - openFile(/var/log/live/log.log,true) call failed. java.io.FileNotFoundException: /var/log/live/log.log (No such file or directory)`

**Comment by fanchaoo** [comment]
mac系统手动把这个文件建下就行了，/var/log/live/log.log
windows改下日志文件目录就可以了

**Comment by fanchaoo** [comment]
close
